title: NSML Documents
longtitle: North Suburban Mathematics League Documents
email: nsml.president@gmail.com
description: >
  Documents for the North Suburban Mathematics League,
  serving the greater Chicago metropolitan area.

theme: just-the-docs

# url: https://docs.nsml.org

url: https://maueroats.github.io/nsml-documents

aux_links:
  Main NSML Site: https://nsml.org
